services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    #restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      NODE_ENV: "production"
      WEBHOOK_URL: https://${LT_SUBDOMAIN}.loca.lt/
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_TRUST_PROXY: true
      N8N_RESTRICT_FILE_ACCESS_TO: "/app_files"
    volumes:
      - n8n_data:/home/node/.n8n
      - ${USER_LOCAL_DATA}:/app_files

volumes:
  n8n_data:
