services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n
    #restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      NODE_ENV: "production"
      WEBHOOK_URL: ${WEBHOOK_URL}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
    depends_on:
      - ngrok
    volumes:
      - n8n_data:/home/node/.n8n

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    #restart: always
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_REGION: ${NGROK_REGION}
    command: ["http", "--domain=${NGROK_DOMAIN}", "n8n:5678"]
    ports:
      - "4040:4040"

volumes:
  n8n_data:
